site_name: GPXRDpy
theme:
  favicon: gpxrdpy_icon.svg
  name: material
  palette:
    primary: amber
  logo: gpxrdpy_icon.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - toc.integrate

nav:
- Introduction: index.md
- Installation: installation.md

repo_url: https://github.com/SanderBorgmans/gpxrdpy
markdown_extensions:
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true